/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mustafatmaca.pathfinder.UI;

import java.awt.CardLayout;

/**
 *
 * @author Muallim
 */
public class AnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    CardLayout cardLayout;
    
    public AnaEkran() {
        initComponents();
        
        cardLayout = (CardLayout)(pnlCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnlAnaEkran = new javax.swing.JSplitPane();
        pnlSekme = new javax.swing.JPanel();
        lblPathfinder = new javax.swing.JLabel();
        btnAnasayfa = new javax.swing.JButton();
        btnRehberBul = new javax.swing.JButton();
        btnRehberOl = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        btnAyarlar = new javax.swing.JButton();
        btnCikisYap = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        crdAnasayfa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        crdRehberBul = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        crdRehberOl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        crdProfil = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        crdAyarlar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlSekme.setBackground(new java.awt.Color(51, 51, 51));
        pnlSekme.setPreferredSize(new java.awt.Dimension(200, 575));

        lblPathfinder.setBackground(new java.awt.Color(51, 51, 51));
        lblPathfinder.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblPathfinder.setForeground(new java.awt.Color(255, 204, 51));
        lblPathfinder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPathfinder.setText("Pathfinder");

        btnAnasayfa.setBackground(new java.awt.Color(255, 204, 51));
        btnAnasayfa.setText("Ana Sayfa");
        btnAnasayfa.setBorderPainted(false);
        btnAnasayfa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAnasayfa.setFocusPainted(false);
        btnAnasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnasayfaActionPerformed(evt);
            }
        });

        btnRehberBul.setBackground(new java.awt.Color(255, 204, 51));
        btnRehberBul.setText("Rehber Bul");
        btnRehberBul.setBorderPainted(false);
        btnRehberBul.setFocusPainted(false);
        btnRehberBul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRehberBulActionPerformed(evt);
            }
        });

        btnRehberOl.setBackground(new java.awt.Color(255, 204, 51));
        btnRehberOl.setText("Rehber Ol");
        btnRehberOl.setBorderPainted(false);
        btnRehberOl.setFocusPainted(false);
        btnRehberOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRehberOlActionPerformed(evt);
            }
        });

        btnProfil.setBackground(new java.awt.Color(255, 204, 51));
        btnProfil.setText("Profil");
        btnProfil.setBorderPainted(false);
        btnProfil.setFocusPainted(false);
        btnProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilActionPerformed(evt);
            }
        });

        btnAyarlar.setBackground(new java.awt.Color(255, 204, 51));
        btnAyarlar.setText("Ayarlar");
        btnAyarlar.setBorderPainted(false);
        btnAyarlar.setFocusPainted(false);
        btnAyarlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyarlarActionPerformed(evt);
            }
        });

        btnCikisYap.setBackground(new java.awt.Color(255, 204, 51));
        btnCikisYap.setText("Çıkış Yap");
        btnCikisYap.setBorderPainted(false);
        btnCikisYap.setFocusPainted(false);
        btnCikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSekmeLayout = new javax.swing.GroupLayout(pnlSekme);
        pnlSekme.setLayout(pnlSekmeLayout);
        pnlSekmeLayout.setHorizontalGroup(
            pnlSekmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSekmeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSekmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPathfinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnasayfa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRehberBul, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnProfil, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnAyarlar, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnCikisYap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnRehberOl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSekmeLayout.setVerticalGroup(
            pnlSekmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSekmeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPathfinder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAnasayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRehberBul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRehberOl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAyarlar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCikisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        spnlAnaEkran.setLeftComponent(pnlSekme);

        pnlCards.setPreferredSize(new java.awt.Dimension(573, 575));
        pnlCards.setLayout(new java.awt.CardLayout());

        crdAnasayfa.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ana Sayfa");

        javax.swing.GroupLayout crdAnasayfaLayout = new javax.swing.GroupLayout(crdAnasayfa);
        crdAnasayfa.setLayout(crdAnasayfaLayout);
        crdAnasayfaLayout.setHorizontalGroup(
            crdAnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crdAnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdAnasayfaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        crdAnasayfaLayout.setVerticalGroup(
            crdAnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crdAnasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdAnasayfaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlCards.add(crdAnasayfa, "pnlCard1");

        crdRehberBul.setBackground(new java.awt.Color(153, 255, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rehber Bul");

        javax.swing.GroupLayout crdRehberBulLayout = new javax.swing.GroupLayout(crdRehberBul);
        crdRehberBul.setLayout(crdRehberBulLayout);
        crdRehberBulLayout.setHorizontalGroup(
            crdRehberBulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crdRehberBulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdRehberBulLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        crdRehberBulLayout.setVerticalGroup(
            crdRehberBulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crdRehberBulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdRehberBulLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlCards.add(crdRehberBul, "pnlCard2");

        crdRehberOl.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Rehber Ol");

        javax.swing.GroupLayout crdRehberOlLayout = new javax.swing.GroupLayout(crdRehberOl);
        crdRehberOl.setLayout(crdRehberOlLayout);
        crdRehberOlLayout.setHorizontalGroup(
            crdRehberOlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(crdRehberOlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdRehberOlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        crdRehberOlLayout.setVerticalGroup(
            crdRehberOlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(crdRehberOlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdRehberOlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlCards.add(crdRehberOl, "pnlCard3");

        crdProfil.setBackground(new java.awt.Color(51, 153, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Profil");

        javax.swing.GroupLayout crdProfilLayout = new javax.swing.GroupLayout(crdProfil);
        crdProfil.setLayout(crdProfilLayout);
        crdProfilLayout.setHorizontalGroup(
            crdProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crdProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdProfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        crdProfilLayout.setVerticalGroup(
            crdProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(crdProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crdProfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlCards.add(crdProfil, "pnlCard4");

        crdAyarlar.setBackground(new java.awt.Color(51, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ayarlar");

        javax.swing.GroupLayout crdAyarlarLayout = new javax.swing.GroupLayout(crdAyarlar);
        crdAyarlar.setLayout(crdAyarlarLayout);
        crdAyarlarLayout.setHorizontalGroup(
            crdAyarlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crdAyarlarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        crdAyarlarLayout.setVerticalGroup(
            crdAyarlarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crdAyarlarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlCards.add(crdAyarlar, "pnlCard5");

        spnlAnaEkran.setRightComponent(pnlCards);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnlAnaEkran)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spnlAnaEkran, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnasayfaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard1");
    }//GEN-LAST:event_btnAnasayfaActionPerformed

    private void btnRehberBulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRehberBulActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard2");
    }//GEN-LAST:event_btnRehberBulActionPerformed

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard4");
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnAyarlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyarlarActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard5");
    }//GEN-LAST:event_btnAyarlarActionPerformed

    private void btnCikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisYapActionPerformed
        // TODO add your handling code here:
        GirisEkrani girisEkrani = new GirisEkrani();
        girisEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnCikisYapActionPerformed

    private void btnRehberOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRehberOlActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard3");
    }//GEN-LAST:event_btnRehberOlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnasayfa;
    private javax.swing.JButton btnAyarlar;
    private javax.swing.JButton btnCikisYap;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnRehberBul;
    private javax.swing.JButton btnRehberOl;
    private javax.swing.JPanel crdAnasayfa;
    private javax.swing.JPanel crdAyarlar;
    private javax.swing.JPanel crdProfil;
    private javax.swing.JPanel crdRehberBul;
    private javax.swing.JPanel crdRehberOl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPathfinder;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlSekme;
    private javax.swing.JSplitPane spnlAnaEkran;
    // End of variables declaration//GEN-END:variables
}
