/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mustafatmaca.pathfinder.UI;


import com.mustafatmaca.pathfinder.database.VeriTabani;
import com.mustafatmaca.pathfinder.models.Kullanıcı;

import javax.swing.*;

/**
 * @author Muallim
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form GirisEkrani
     */
    public GirisEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        tfKullaniciAdi = new javax.swing.JTextField();
        pfSifre = new javax.swing.JPasswordField();
        lblPathfinder = new javax.swing.JLabel();
        btnGirisYap = new javax.swing.JButton();
        btnKayitOl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblKullaniciAdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKullaniciAdi.setForeground(new java.awt.Color(255, 204, 51));
        lblKullaniciAdi.setText("Kullanıcı Adı : ");

        lblSifre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSifre.setForeground(new java.awt.Color(255, 204, 51));
        lblSifre.setText("Şifre : ");

        tfKullaniciAdi.setBackground(new java.awt.Color(255, 204, 51));
        tfKullaniciAdi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfKullaniciAdi.setToolTipText("Kullanıcı adınızı giriniz.");
        tfKullaniciAdi.setBorder(null);

        pfSifre.setBackground(new java.awt.Color(255, 204, 51));
        pfSifre.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        pfSifre.setToolTipText("Şifrenizi giriniz.");
        pfSifre.setBorder(null);

        lblPathfinder.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblPathfinder.setForeground(new java.awt.Color(255, 204, 51));
        lblPathfinder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPathfinder.setText("Pathfinder");

        btnGirisYap.setBackground(new java.awt.Color(255, 204, 51));
        btnGirisYap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGirisYap.setText("Giriş Yap");
        btnGirisYap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGirisYap.setFocusPainted(false);
        btnGirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisYapActionPerformed(evt);
            }
        });

        btnKayitOl.setBackground(new java.awt.Color(255, 204, 51));
        btnKayitOl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKayitOl.setText("Kayıt Ol");
        btnKayitOl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKayitOl.setFocusPainted(false);
        btnKayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitOlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPathfinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfSifre)
                    .addComponent(tfKullaniciAdi)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPathfinder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pfSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitOlActionPerformed
        KayitEkrani kayitEkrani = new KayitEkrani();
        kayitEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnKayitOlActionPerformed

    private void btnGirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisYapActionPerformed
        VeriTabani VeriTabani = new VeriTabani();

        if (!tfKullaniciAdi.getText().isEmpty() && !pfSifre.getText().isEmpty()){
            Kullanıcı kullanıcı = new Kullanıcı(tfKullaniciAdi.getText(), pfSifre.getText());
            if(VeriTabani.girisKontrol(VeriTabani, kullanıcı)){

                AnaEkran anaEkran = new AnaEkran();
                anaEkran.kullanıcıBilgi(kullanıcı);
                anaEkran.setVisible(true);
                setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(this, "Hesap Bulunamadı!");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Alanları boş bırakmayınız!");
        }


    }//GEN-LAST:event_btnGirisYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGirisYap;
    private javax.swing.JButton btnKayitOl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblPathfinder;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JPasswordField pfSifre;
    private javax.swing.JTextField tfKullaniciAdi;
    // End of variables declaration//GEN-END:variables
}
