/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mustafatmaca.pathfinder.UI;

import com.mustafatmaca.pathfinder.database.VeriTabani;
import com.mustafatmaca.pathfinder.models.Kullanici;

import javax.swing.*;

/**
 * @author Muallim
 */
public class KayitEkrani extends javax.swing.JFrame {

    /**
     * Creates new form KayitEkrani
     */
    public KayitEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKayitOlustur = new javax.swing.JLabel();
        lblKullaniciAdi = new javax.swing.JLabel();
        lblSifre = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblGsm = new javax.swing.JLabel();
        lblSehir = new javax.swing.JLabel();
        tfKullaniciAdi = new javax.swing.JTextField();
        pfSifre = new javax.swing.JPasswordField();
        tfEmail = new javax.swing.JTextField();
        tfGsm = new javax.swing.JTextField();
        tfSehir = new javax.swing.JTextField();
        btnHesabimVar = new javax.swing.JButton();
        btnKayitOl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lblKayitOlustur.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        lblKayitOlustur.setForeground(new java.awt.Color(255, 204, 51));
        lblKayitOlustur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKayitOlustur.setText("Kayıt Oluştur");

        lblKullaniciAdi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKullaniciAdi.setForeground(new java.awt.Color(255, 204, 51));
        lblKullaniciAdi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKullaniciAdi.setText("Kullanıcı Adı : ");

        lblSifre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSifre.setForeground(new java.awt.Color(255, 204, 51));
        lblSifre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSifre.setText("Şifre : ");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 204, 51));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email : ");

        lblGsm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGsm.setForeground(new java.awt.Color(255, 204, 51));
        lblGsm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGsm.setText("GSM : ");

        lblSehir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSehir.setForeground(new java.awt.Color(255, 204, 51));
        lblSehir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSehir.setText("Şehir : ");

        tfKullaniciAdi.setBackground(new java.awt.Color(255, 204, 51));
        tfKullaniciAdi.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfKullaniciAdi.setToolTipText("Kullanıcı adınızı giriniz.");
        tfKullaniciAdi.setBorder(null);

        pfSifre.setBackground(new java.awt.Color(255, 204, 51));
        pfSifre.setToolTipText("Şifrenizi giriniz.");
        pfSifre.setBorder(null);

        tfEmail.setBackground(new java.awt.Color(255, 204, 51));
        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfEmail.setToolTipText("Email giriniz.");
        tfEmail.setBorder(null);

        tfGsm.setBackground(new java.awt.Color(255, 204, 51));
        tfGsm.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfGsm.setToolTipText("GSM giriniz.");
        tfGsm.setBorder(null);

        tfSehir.setBackground(new java.awt.Color(255, 204, 51));
        tfSehir.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tfSehir.setToolTipText("Şehir giriniz.");
        tfSehir.setBorder(null);

        btnHesabimVar.setBackground(new java.awt.Color(255, 204, 51));
        btnHesabimVar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHesabimVar.setText("Hesabım Var");
        btnHesabimVar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHesabimVar.setFocusPainted(false);
        btnHesabimVar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHesabimVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesabimVarActionPerformed(evt);
            }
        });

        btnKayitOl.setBackground(new java.awt.Color(255, 204, 51));
        btnKayitOl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKayitOl.setText("Kayıt Ol");
        btnKayitOl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKayitOl.setFocusPainted(false);
        btnKayitOl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitOlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKayitOlustur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblGsm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSifre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSehir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHesabimVar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfSehir)
                    .addComponent(tfEmail)
                    .addComponent(tfKullaniciAdi)
                    .addComponent(tfGsm)
                    .addComponent(pfSifre))
                .addGap(68, 99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblKayitOlustur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tfKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(pfSifre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGsm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGsm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSehir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSehir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHesabimVar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHesabimVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesabimVarActionPerformed
        // TODO add your handling code here:
        GirisEkrani girisEkrani = new GirisEkrani();
        girisEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnHesabimVarActionPerformed

    private void btnKayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitOlActionPerformed
        // TODO add your handling code here:
        VeriTabani VeriTabani = new VeriTabani();

        if (!tfKullaniciAdi.getText().isEmpty() && !pfSifre.getText().isEmpty() && !tfEmail.getText().isEmpty() && !tfGsm.getText().isEmpty() && !tfSehir.getText().isEmpty()){
            Kullanici kullanıcı = new Kullanici(tfKullaniciAdi.getText(), pfSifre.getText(), tfEmail.getText(), tfGsm.getText(), tfSehir.getText());
            if(!VeriTabani.kayitKontrol(VeriTabani, kullanıcı)){
                VeriTabani.kayitOlustur(VeriTabani, kullanıcı);

                GirisEkrani girisEkrani = new GirisEkrani();
                girisEkrani.setVisible(true);
                setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(this, "Bu email adresine kayıtlı bir hesap var!");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Alanları boş bırakmayınız!");
        }



    }//GEN-LAST:event_btnKayitOlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHesabimVar;
    private javax.swing.JButton btnKayitOl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGsm;
    private javax.swing.JLabel lblKayitOlustur;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblSehir;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JPasswordField pfSifre;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfGsm;
    private javax.swing.JTextField tfKullaniciAdi;
    private javax.swing.JTextField tfSehir;
    // End of variables declaration//GEN-END:variables
}
